name: SilverStone Consulting Corp
favicon: null
layout_spectrum: 0.47510679834522307
typography_spectrum: 0.6197607144713402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8420615729410201
  lightness: 0.06710255658254027
  saturation: 0.22326738643459976
  rhythmicContrast: 0.7693320554681122
purpose: []
