name: SilverStone Consulting Corp
favicon: null
layout_spectrum: 0.25931
typography_spectrum: 0.89915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7b7b7b'
    - '#595959'
    - '#333333'
    - '#0c0c0c'
  brandStrength: 1
  lightness: 0.06710255658254027
  saturation: 0.25
  rhythmicContrast: 0.7693320554681122
purpose: []
